Feature/3 transfer
PROG17/BlomsBank pull request #3
Opened 2018-11-22 09:36 UTC by OliviaDenbuW

@AndBlo jag är färdig med ruta 5. Du kan kolla igenom det :)

2018-11-22 11:31 UTC, AndBlo requested changes
Grymt jobbat Olivia 👍 Bra jobbat med unittesterna, koden är i det hela taget snygg och konsekvent :)
En mindre petitess bara, eftersom jag har lagt till kredit på kontona så behöver villkoret i Transfer på BankService (rad 56) kolla ActualSum istället för Balance.
Alltså, gör om detta:
```cs
if (sum > fromAccount.Balance) return false;
            toAccount.Balance += sum;
            fromAccount.Balance -= sum;
```
till
```cs
if (sum > fromAccount.ActualSum) return false;
            toAccount.Balance += sum;
            fromAccount.Balance -= sum;
```

2018-11-28 11:45 UTC, OliviaDenbuW commented
@AndBlo Tack! :) jag ska kolla på det nu!

2018-11-28 12:06 UTC, OliviaDenbuW commented
@AndBlo nu har jag gjort det! Kolla om du tycker det blev bra :)

2018-11-29 12:55 UTC, AndBlo approved these changes
Ser bra ut!

2018-11-29 12:57 UTC, merged